### ISSUE TITLE
Testing Out the SDL 2.0 Port - Main Screen slow to/fails to load

### ISSUE THREAD

**Issue by jserio1869** [libsdl-org/Maelstrom#1]
Hi Sam,

I am testing out the SDL 2.0 Port version of Maelstrom (3.0.7) and have everything running using the most recent SDL2 (2.25.1) and SDL2_net 2.2.0. The fatal error from the "pitch" issue has been fixed, as well as the text parsing issue!

-Noticed that after the Loading screen, the main menu does not always populate. It will populate if one of the button options is hit.
-Noticed that the "OK" in the "C" configure option window does not always close out this window. Also, sometimes have to hit "C" twice to get configure window to appear.

I will try some gameplay during this upcoming Thanksgiving week!

Joe Serio

**Comment by jserio1869** [comment]
Did a bit more testing at the beginning of holiday week - seems a lot crisper now. May have been lagging a bit due to needing a restart or something. Will close to no work needed.

**Comment by slouken** [comment]
FYI, I'm planning on shipping the classic Maelstrom port on Steam, Google Play, and the Apple Store on May 1, and I need testers on all of those platforms. I especially need help testing multiplayer and mobile, and need lots of screenshots and gameplay videos and help spreading the word.

If you are interested in testing, please send me e-mail at [slouken@libsdl.org](mailto:slouken@libsdl.org) and let me know platforms you'll be testing!
